### ISSUE TITLE
team chat can be listened from people outside team

### ISSUE THREAD

**Issue by xion87** [BentoBoxWorld/Chat#14]
I don't know how but when i talk to team chat, sometimes random people can hear the team chat, i think is because the chat team is unidified for all players also in other teams

**Comment by tastybento** [comment]
That shouldn’t happen of course. I’ll have to investigate if there’s a way it could happen.

**Comment by tastybento** [comment]
Island chat does enable people on your island to see the chat even if they are not in your team. Do you have that switched on too?

**Comment by wellnesscookie** [comment]
We are using it too and have no problems. The only similar problem that occured is the one that tasty mentioned previously, it was because players were used to ASB as then only TeamChat existed, but not IslandChat as well. They kept writing in /is chat and all players on that island were able to read it which is working as intended ofc. They should use /is tc instead.

**Comment by xion87** [comment]
that stuff happened random, and people don't have the permission to use the island chat command, just the teamchat

**Comment by wellnesscookie** [comment]
Which version of addon are you running? The first release has a bug in which trusted, cooped and banned players can see teamchat too

**Comment by xion87** [comment]
Chat-1.0.4

**Comment by wellnesscookie** [comment]
Hmm, as far as I can see, tasty decided to consider coops and trusted players as part of a team too. Are the players that receive those messages cooped or trusted?
